title: Hello marimoa!
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.naver.com/sky_yoon1" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Marimoa'
  last_name: '박소윤'
  cv: 'https://marimoa0924.github.io/'
  avatar: '/images/avatar.png'
  github_username: 'marimoa0924'
  email: 'sky_yoon1@naver.com'
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


